version: "3.9"
services:
  postgres:
    container_name: twenty_postgres
    image: twentycrm/twenty-postgres:latest
    volumes:
    - twenty_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
    ports:
      - "5432:5432"
volumes:
  twenty_db_data:
    name: twenty_db_data

