extends: existence
message: "Avoid using first person (such as '%s')"
ignorecase: true
level: error
nonword: true
tokens:
  - (?:^|\s)I\s
  - (?:^|\s)I,\s
  - \bI'd\b
  - \bI'll\b
  - \bI'm\b
  - \bI've\b
  - \bme\b
  - \bmy\b
  - \bmine\b